/// Flutter icons Custom_Icon_Login
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icon_Login
///      fonts:
///       - asset: fonts/Custom_Icon_Login.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_Icon_Login {
  Custom_Icon_Login._();

  static const _kFontFam = 'Custom_Icon_Login';
  static const String? _kFontPkg = null;

  static const IconData left_arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
